export const themes = {
  apple: {
    colors: {
      primary: "#007AFF",
      background: "#F9F9F9",
      text: "#333",
      success: "#28a745",
      error: "#dc3545",
      warning: "#ffc107",
      info: "#007bff",
      hoverBackground: "#005bb5",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #d1d1d6",
    borderRadius: "8px",
    font: "San Francisco, Arial, sans-serif",
    boxShadow: "0 1px 2px rgba(0,0,0,0.1)",
    header: {
      logoFontSize: "24px",
      navGap: "24px",
      navItemFontSize: "18px",
    },
  },
  google: {
    colors: {
      primary: "#4285F4",
      background: "#FFFFFF",
      text: "#202124",
      success: "#34a853",
      error: "#ea4335",
      warning: "#fbbc05",
      info: "#4285f4",
      hoverBackground: "#3367d6",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #e0e0e0",
    borderRadius: "4px",
    font: "Roboto, Arial, sans-serif",
    boxShadow: "0 2px 5px rgba(0,0,0,0.15)",
    header: {
      logoFontSize: "22px",
      navGap: "20px",
      navItemFontSize: "16px",
    },
  },
  microsoft: {
    colors: {
      primary: "#0078D4",
      background: "#F3F2F1",
      text: "#323130",
      success: "#107c10",
      error: "#d83b01",
      warning: "#ffb900",
      info: "#0078d4",
      hoverBackground: "#005a9e",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #d3d3d3",
    borderRadius: "2px",
    font: "Segoe UI, Arial, sans-serif",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    header: {
      logoFontSize: "24px",
      navGap: "20px",
      navItemFontSize: "18px",
    },
  },
  airbnb: {
    colors: {
      primary: "#FF385C",
      background: "#FAFAFA",
      text: "#484848",
      success: "#008489",
      error: "#ff385c",
      warning: "#fcbc05",
      info: "#ff385c",
      hoverBackground: "#e12d50",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #e0e0e0",
    borderRadius: "12px",
    font: "Circular, Arial, sans-serif",
    boxShadow: "0 4px 8px rgba(0,0,0,0.2)",
    header: {
      logoFontSize: "26px",
      navGap: "28px",
      navItemFontSize: "20px",
    },
  },
  spotify: {
    colors: {
      primary: "#1DB954",
      background: "#121212",
      text: "#FFFFFF",
      success: "#1db954",
      error: "#e22134",
      warning: "#f1c40f",
      info: "#1db954",
      hoverBackground: "#1aa34a",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #333333",
    borderRadius: "8px",
    font: "Spotify Circular, Arial, sans-serif",
    boxShadow: "0 4px 8px rgba(0,0,0,0.3)",
    header: {
      logoFontSize: "28px",
      navGap: "24px",
      navItemFontSize: "18px",
    },
  },
  uber: {
    colors: {
      primary: "#000000",
      background: "#FFFFFF",
      text: "#333333",
      success: "#28a745",
      error: "#dc3545",
      warning: "#ffc107",
      info: "#000000",
      hoverBackground: "#333333",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #e0e0e0",
    borderRadius: "6px",
    font: "Uber Move, Arial, sans-serif",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    header: {
      logoFontSize: "20px",
      navGap: "16px",
      navItemFontSize: "16px",
    },
  },
  notion: {
    colors: {
      primary: "#2F3437",
      background: "#FFFFFF",
      text: "#2F3437",
      success: "#00b894",
      error: "#e74c3c",
      warning: "#f39c12",
      info: "#2f3437",
      hoverBackground: "#1f2427",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #e0e0e0",
    borderRadius: "4px",
    font: "Inter, Arial, sans-serif",
    boxShadow: "none",
    header: {
      logoFontSize: "24px",
      navGap: "20px",
      navItemFontSize: "18px",
    },
  },
  stripe: {
    colors: {
      primary: "#635BFF",
      background: "#F6F9FC",
      text: "#32325D",
      success: "#24b47e",
      error: "#e25950",
      warning: "#f5a623",
      info: "#635bff",
      hoverBackground: "#5148c7",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #d1d1d6",
    borderRadius: "4px",
    font: "Stripe Sans, Arial, sans-serif",
    boxShadow: "0 0 8px rgba(50,50,93,0.1)",
    header: {
      logoFontSize: "22px",
      navGap: "18px",
      navItemFontSize: "16px",
    },
  },
  netflix: {
    colors: {
      primary: "#E50914",
      background: "#141414",
      text: "#FFFFFF",
      success: "#46d369",
      error: "#e50914",
      warning: "#f5a623",
      info: "#e50914",
      hoverBackground: "#b00610",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid #333333",
    borderRadius: "0",
    font: "Helvetica Neue, Arial, sans-serif",
    boxShadow: "0 2px 5px rgba(0,0,0,0.5)",
    header: {
      logoFontSize: "28px",
      navGap: "24px",
      navItemFontSize: "20px",
    },
  },
  figma: {
    colors: {
      primary: "#0ACF83",
      background: "#FFFFFF",
      text: "#333333",
      success: "#0acf83",
      error: "#ff453a",
      warning: "#ff9f0a",
      info: "#0acf83",
      hoverBackground: "#08b773",
      hoverColor: "#FFFFFF",
    },
    border: "1px solid black",
    borderRadius: "8px",
    font: "Gotham, Arial, sans-serif",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    header: {
      logoFontSize: "26px",
      navGap: "22px",
      navItemFontSize: "18px",
    },
  },
};
